# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Release

on:
  push:
  pull_request:
    branches:
      - production

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - name: Install dependencies 🚀
        run: yarn install --immutable
      - name: Run lint 🔍
        run: yarn test:lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - name: Install dependencies 🚀
        run: yarn install --immutable
      - name: Run test 🔍
        run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: "@tsed/logger"
          path-to-lcov: './packages/logger/coverage/lcov.info'

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - name: Install dependencies 🚀
        run: yarn install --immutable
      - name: Build 🚧
        run: yarn build

  deploy-packages:
    runs-on: ubuntu-latest
    needs: [ test, build, lint ]
    if: ${{ github.event_name != 'pull_request' && (contains(github.ref, 'production') || contains(github.ref, 'alpha')  || contains(github.ref, 'beta') || contains(github.ref, 'rc')) }}


    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - name: Install dependencies 🚀
        run: yarn install --immutable
      - name: Release packages 🔖
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: yarn release
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            package.json
            packages/*/package.json

  publish-pages:
    runs-on: ubuntu-latest
    needs: deploy-packages
    if: ${{ github.event_name != 'pull_request' && (contains(github.ref, 'production') || contains(github.ref, 'alpha')  || contains(github.ref, 'beta') || contains(github.ref, 'rc')) }}
    steps:
      - name: "Trigger Website workflow"
        run: |
          curl -X POST  https://api.github.com/repos/tsedio/logger/actions/workflows/website.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{secrets.GH_TOKEN}}' \
          --data '{"ref": "${{github.ref_name}}"}'
